field_mappings_incout = {
    "environment" : ["Environment:"],
    "aba" : ["ABA:"],
    "mode" : ["Mode:"],
    "service_unit" : ["Service Unit:","Unit:","Service"],
    "cycle_date" : ["Cycle Date:","Date:","Cycle"],
    "system_date/time" : ["System Date/Time:","Date/Time:","System"],
    "status" : ["Status:"],
    "message_type" : ["Message Type:","Type:","Message"],
    "create_time" : ["Create Time:","Time:","Create"],
    "test/prod" : ["Test/Prod:"],
    "imad" : ["IMAD:"],
    "omad" : ["OMAD:"],
    "sender_aba" : ["Sender ABA {3100}:"],
    "receiver_aba" : ["Receiver ABA {3400}:"],
    "amount" : ["Amount {2000}:"],
    "type/subtype_code" : ["Type/Subtype Code {1510}:"],
    "business_function" : ["Business Function {3600}:"],
    "sender_reference" : ["Sender Reference {3320}:"],
    "reference_for_beneficary" : ["Reference for Beneficiary {4320}:"],
    "originator_to_beneficiary_information_text" : ["Originator to Beneficiary Information {6000}"],
    "originator_id" : ["ID Code:"],
    "originator_identifier" : ["Identifier:"],
    "originator_name" : ["Name:"],
    "originator_address" : ["Address:"], 
    "beneficiary_id" : ["ID Code:"],
    "beneficiary_identifier" : ["Identifier:"],
    "beneficiary_name" : ["Name:"],
    "beneficiary_address" : ["Address:"],
    "beneficiary_information_text" : ["Beneficiary Information {6400}"],
}
originator_mappings = {
    "originator_id" : ["ID Code:"],
    "originator_identifier" : ["Identifier:"],
    "originator_name" : ["Name:"],
    "originator_address" : ["Address:"],
}
beneficiary_mappings = {
    "beneficiary_id" : ["ID Code:"],
    "beneficiary_identifier" : ["Identifier:"],
    "beneficiary_name" : ["Name:"],
    "beneficiary_address" : ["Address:"],
}